version: '3.8'

services:
  carlog-backend:
    build: .
    container_name: carlog-backend
    restart: always
    env_file:
      - .env
    networks:
      - carlog-network

networks:
  carlog-network:
    external: true
