version: '3.8'

services:
  carlog-backend:
    build: .
    container_name: carlog-backend
    restart: always
    env_file:
      - .env
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://carlog-mysql:3306/carlog_db?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC
    networks:
      - carlog-network

networks:
  carlog-network:
    external: true
