version: '3.8'

services:
  # Servicio de Base de Datos MySQL
  mysqldb:
    image: mysql:8.0
    container_name: carlog-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}     # Contraseña maestra
      MYSQL_DATABASE: carlog_db        # Crea la BBDD automáticamente
      MYSQL_USER: ${DB_USER}         # Usuario específico para la App
      MYSQL_PASSWORD: ${DB_PASSWORD} # Contraseña para la App
    ports:
      - "127.0.0.1:3306:3306"                    # Expone el puerto al exterior
    volumes:
      - mysql_data:/var/lib/mysql      # Persistencia de datos

volumes:
  mysql_data: