version: '3.8'

services:
  mysqldb:
    image: mysql:8.0
    container_name: carlog-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: carlog_db # Tu base de datos real
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - "127.0.0.1:3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - carlog-network # Enlazamos el contenedor a la red

volumes:
  mysql_data:

# Creamos la red para que sea visible desde fuera
networks:
  carlog-network:
    name: carlog-network
