spring.application.name=backend
spring.datasource.url=jdbc:mysql://${DB_HOST:127.0.0.1}:3306/carlog_db?useSSL=${isSecure:false}&serverTimezone=UTC
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
logging.level.org.springframework.security=DEBUG

##Configuración JPA
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show.sql=false
spring.jpa.properties.hibernate.format_sql=false
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

##Configuración del puerto del servidor
server.port=8081

application.security.jwt.secret-key=${JWT_SECRET_KEY}
application.security.jwt.expiration=86400000

springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html

springdoc.model-converters.pageable-converter.enabled=true
springdoc.remove-broken-reference-definitions=true

springdoc.default-flat-param-object=true
springdoc.use-fqn=true
springdoc.ignored-types=java.security.Principal,org.springframework.security.core.Authentication
springdoc.api-docs.resolve-schema-properties=false
springdoc.show-actuator=false
